chore(deps): Update aws-sdk-go from v1.34.32 to v1.42.37
This version of the AWS SDK for go includes API changes to support
ED25519 keys for EC2 instance connect.

Prior to this update users with ED25519 keys would recieve the following
error message when trying to use `sigil ssh`:

```
Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 256, SendSSHPublicKeyInput.SSHPublicKey.
```

After this update, `sigil ssh` works as expected.

---

AWS release announcement:
https://aws.amazon.com/about-aws/whats-new/2022/01/ed25519-keys-authentication-ec2-instance-connect/

AWS SDK Go Release:
https://github.com/aws/aws-sdk-go/releases/tag/v1.42.37